version: '3.9'


services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: JavaFinancy
      MYSQL_USER: fabian
      MYSQL_USER_PASSWORD: fabian
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: