CREATE TABLE budgets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    value BIGINT NOT NULL,
    date DATE NOT NULL DEFAULT (CURDATE())
);

CREATE TABLE incomes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    value BIGINT NOT NULL,
    date DATE NOT NULL DEFAULT (CURDATE())
);

CREATE TABLE savings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    value BIGINT NOT NULL,
    category ENUM('AHORRO', 'INVERSION', 'TRANSPORTE', 'VIVIENDA') NOT NULL,
    date DATE NOT NULL DEFAULT (CURDATE())
);

CREATE TABLE expenses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    value BIGINT NOT NULL,
    category ENUM('AHORRO', 'INVERSION', 'OTRO') NOT NULL,
    date DATE NOT NULL DEFAULT (CURDATE())
);

CREATE TABLE projections (
    id INT AUTO_INCREMENT PRIMARY KEY,
    projected_budgets BIGINT NOT NULL,
    projected_expenses BIGINT NOT NULL,
    projected_incomes BIGINT NOT NULL,
    projected_savings BIGINT NOT NULL,
    months INT(12) NOT NULL
)