CREATE TABLE budgets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    value BIGINT NOT NULL
);

CREATE TABLE incomes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    value BIGINT NOT NULL,
    date DATE NOT NULL
);

CREATE TABLE savings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    value BIGINT NOT NULL,
    category ENUM('AHORRO', 'INVERSION', 'OTRO') NOT NULL
);

CREATE TABLE expenses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    value BIGINT NOT NULL,
    category ENUM('AHORRO', 'INVERSION', 'OTRO') NOT NULL,
    date DATE NOT NULL
);