version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: JavaFinancy
      MYSQL_USER: fabian
      MYSQL_USER_PASSWORD: fabian
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql: